### ISSUE TITLE
May I know how to cite this repository / dataset?

### ISSUE THREAD

**Issue by shivanraptor** [bluebat/msgchi#1]
May I know how to cite this repository / dataset? I would like to cite this in my conference paper. In BibTex format would be great, thanks.

**Comment by bluebat** [comment]
Thanks for your citation.
I have no particular opinion. What do you recommend?

**Comment by shivanraptor** [comment]
In Overleaf LaTex editor, it suggests:

```
@misc{githubGitHubBluebatmsgchi,
	author = {},
	title = {{G}it{H}ub - bluebat/msgchi: {C}reating a translation catalog for chinese locales --- github.com},
	howpublished = {\url{https://github.com/bluebat/msgchi}},
	year = {},
	note = {[Accessed 23-May-2023]},
}
```

May I know who should I put in the author and year field? I am unsure about the title as well.

Also, are there any associated journal/conference papers that I can add to the citation? Thanks again.

**Comment by bluebat** [comment]
Author: 趙惟倫(Wei-Lun Chao)
Year: 2017~2023
Title in chinese: 軟體訊息本地化前置翻譯工具

There are some presentations:
https://speakerdeck.com/bluebat/msgchi-l10n-tool
https://speakerdeck.com/bluebat/look-at-yue-desktop
https://speakerdeck.com/bluebat/locales-for-chinese-dialects
https://speakerdeck.com/bluebat/free-software-localization

and further projects:
https://github.com/chinese-opendesktop/glibc-sinitic-langpacks
https://github.com/chinese-opendesktop/language-pack-sinitic
